export const match2v2v1v1v1v1 = {
    playerId: 19627663,
    match: {
        matchId: 326280553,
        started: '2024-07-14T17:18:12.000Z',
        finished: '2024-07-14T17:27:44.000Z',
        leaderboardId: 'qp_rm_team',
        leaderboardName: 'Quick Play Team Random Map',
        name: 'AUTOMATCH',
        server: null,
        internalLeaderboardId: 19,
        map: 'rm_nomad',
        mapName: 'Nomad',
        mapImageUrl: 'https://backend.cdn.aoe2companion.com/public/aoe2/de/maps/rm_nomad.png',
        privacy: 2,
        difficulty: 3,
        startingAge: 2,
        fullTechTree: false,
        allowCheats: false,
        empireWarsMode: true,
        endingAge: 5,
        gameMode: 'random_map',
        gameModeName: 'Random Map',
        lockSpeed: true,
        lockTeams: false,
        mapSize: 168,
        population: 200,
        hideCivs: false,
        recordGame: true,
        regicideMode: true,
        gameVariant: 2,
        resources: 1,
        sharedExploration: false,
        speed: 2,
        speedName: 'Normal',
        suddenDeathMode: true,
        teamPositions: true,
        teamTogether: true,
        treatyLength: 0,
        turboMode: true,
        victory: 9,
        revealMap: 0,
        scenario: null,
        teams: [
            {
                teamId: 1,
                players: [
                    {
                        profileId: 19627663,
                        name: 'natanael_640',
                        rating: 1137,
                        ratingDiff: -17,
                        civ: 'chinese',
                        civName: 'Chinese',
                        civImageUrl: 'https://backend.cdn.aoe2companion.com/public/aoe2/de/civilizations/chinese.png',
                        color: 2,
                        colorHex: '#FF0000',
                        slot: 0,
                        status: 0,
                        team: 1,
                        replay: false,
                        won: false,
                        country: null,
                        verified: false,
                        avatarHash: null,
                        avatarSmallUrl: null,
                        avatarMediumUrl: null,
                        avatarFullUrl: null,
                    },
                    {
                        profileId: 19640529,
                        name: 'matiabboud94',
                        rating: 1133,
                        ratingDiff: -17,
                        civ: 'mongols',
                        civName: 'Mongols',
                        civImageUrl: 'https://backend.cdn.aoe2companion.com/public/aoe2/de/civilizations/mongols.png',
                        color: 4,
                        colorHex: '#FFFF00',
                        slot: 2,
                        status: 0,
                        team: 1,
                        replay: false,
                        won: false,
                        country: null,
                        verified: false,
                        avatarHash: null,
                        avatarSmallUrl: null,
                        avatarMediumUrl: null,
                        avatarFullUrl: null,
                    },
                ],
            },
            {
                teamId: 2,
                players: [
                    {
                        profileId: 3141430,
                        name: 'RealMabus666',
                        rating: 1102,
                        ratingDiff: 18,
                        civ: 'aztecs',
                        civName: 'Aztecs',
                        civImageUrl: 'https://backend.cdn.aoe2companion.com/public/aoe2/de/civilizations/aztecs.png',
                        color: 1,
                        colorHex: '#405BFF',
                        slot: 1,
                        status: 0,
                        team: 2,
                        replay: false,
                        won: true,
                        country: null,
                        verified: false,
                        avatarHash: null,
                        avatarSmallUrl: null,
                        avatarMediumUrl: null,
                        avatarFullUrl: null,
                    },
                    {
                        profileId: 10428329,
                        name: 'Frabossa',
                        rating: 1122,
                        ratingDiff: 17,
                        civ: 'italians',
                        civName: 'Italians',
                        civImageUrl: 'https://backend.cdn.aoe2companion.com/public/aoe2/de/civilizations/italians.png',
                        color: 3,
                        colorHex: '#00FF00',
                        slot: 3,
                        status: 0,
                        team: 2,
                        replay: false,
                        won: true,
                        country: null,
                        verified: false,
                        avatarHash: null,
                        avatarSmallUrl: null,
                        avatarMediumUrl: null,
                        avatarFullUrl: null,
                    },
                ],
            },
            {
                teamId: 3,
                players: [
                    {
                        profileId: 3141430,
                        name: 'RealMabus666',
                        rating: 1102,
                        ratingDiff: 18,
                        civ: 'aztecs',
                        civName: 'Aztecs',
                        civImageUrl: 'https://backend.cdn.aoe2companion.com/public/aoe2/de/civilizations/aztecs.png',
                        color: 1,
                        colorHex: '#405BFF',
                        slot: 1,
                        status: 0,
                        team: 2,
                        replay: false,
                        won: true,
                        country: null,
                        verified: false,
                        avatarHash: null,
                        avatarSmallUrl: null,
                        avatarMediumUrl: null,
                        avatarFullUrl: null,
                    },
                ],
            },
            {
                teamId: 4,
                players: [
                    {
                        profileId: 3141430,
                        name: 'RealMabus666',
                        rating: 1102,
                        ratingDiff: 18,
                        civ: 'aztecs',
                        civName: 'Aztecs',
                        civImageUrl: 'https://backend.cdn.aoe2companion.com/public/aoe2/de/civilizations/aztecs.png',
                        color: 1,
                        colorHex: '#405BFF',
                        slot: 1,
                        status: 0,
                        team: 2,
                        replay: false,
                        won: true,
                        country: null,
                        verified: false,
                        avatarHash: null,
                        avatarSmallUrl: null,
                        avatarMediumUrl: null,
                        avatarFullUrl: null,
                    },
                ],
            },
            {
                teamId: 5,
                players: [
                    {
                        profileId: 3141430,
                        name: 'RealMabus666',
                        rating: 1102,
                        ratingDiff: 18,
                        civ: 'aztecs',
                        civName: 'Aztecs',
                        civImageUrl: 'https://backend.cdn.aoe2companion.com/public/aoe2/de/civilizations/aztecs.png',
                        color: 1,
                        colorHex: '#405BFF',
                        slot: 1,
                        status: 0,
                        team: 2,
                        replay: false,
                        won: true,
                        country: null,
                        verified: false,
                        avatarHash: null,
                        avatarSmallUrl: null,
                        avatarMediumUrl: null,
                        avatarFullUrl: null,
                    },
                ],
            },
            {
                teamId: 6,
                players: [
                    {
                        profileId: 3141430,
                        name: 'RealMabus666',
                        rating: 1102,
                        ratingDiff: 18,
                        civ: 'aztecs',
                        civName: 'Aztecs',
                        civImageUrl: 'https://backend.cdn.aoe2companion.com/public/aoe2/de/civilizations/aztecs.png',
                        color: 1,
                        colorHex: '#405BFF',
                        slot: 1,
                        status: 0,
                        team: 2,
                        replay: false,
                        won: true,
                        country: null,
                        verified: false,
                        avatarHash: null,
                        avatarSmallUrl: null,
                        avatarMediumUrl: null,
                        avatarFullUrl: null,
                    },
                ],
            },
        ],
    },
};