import {Unit, UnitLine, unitLines} from "@nex/data";

const unitIcons = [
    'Sheep',
    'Boar',
    'Kamayuk',
    'Slinger',
    'PlumedArcher',
    'Archer',
    'Crossbowman',
    'Arbalester',
    'Skirmisher',
    'EliteSkirmisher',
    'ImperialSkirmisher',
    'CavalryArcher',
    'HeavyCavalryArcher',
    'Longbowman',
    'ChuKoNu',
    'Mangudai',
    'WarWagon',
    'ElephantArcher',
    'GenoeseCrossbowman',
    'CamelArcher',
    'Genitour',
    'RattanArcher',
    'Kipchak',
    'ScoutCavalry',
    'LightCavalry',
    'Hussar',
    'XolotlWarrior',
    'Knight',
    'Cavalier',
    'Paladin',
    'CamelRider',
    'HeavyCamelRider',
    'ImperialCamelRider',
    'BattleElephant',
    'EliteBattleElephant',
    'SteppeLancer',
    'EliteSteppeLancer',
    'Cataphract',
    'WarElephant',
    'Mameluke',
    'Tarkan',
    'MagyarHuszar',
    'Boyar',
    'Konnik',
    'KonnikDismounted',
    'Leitis',
    'Keshik',
    'Militia',
    'ManAtArms',
    'LongSwordsman',
    'TwoHandedSwordsman',
    'Champion',
    'Spearman',
    'Pikeman',
    'Halberdier',
    'EagleScout',
    'EagleWarrior',
    'EliteEagleWarrior',
    'WoadRaider',
    'ThrowingAxeman',
    'Huskarl',
    'Samurai',
    'TeutonicKnight',
    'Berserk',
    'JaguarWarrior',
    'Condottiero',
    'ShotelWarrior',
    'Gbeto',
    'KarambitWarrior',
    'HandCannoneer',
    'Scorpion',
    'HeavyScorpion',
    'BatteringRam',
    'CappedRam',
    'SiegeRam',
    'Mangonel',
    'Onager',
    'SiegeOnager',
    'BombardCannon',
    'Trebuchet',
    'Petard',
    'FlamingCamel',
    'BallistaElephant',
    'Janissary',
    'Longboat',
    'TurtleShip',
    'Conquistador',
    'SiegeTower',
    'Caravel',
    'OrganGun',
    'Arambai',
    'Galley',
    'WarGalley',
    'Galleon',
    'FireGalley',
    'FireShip',
    'FastFireShip',
    'DemolitionRaft',
    'DemolitionShip',
    'HeavyDemolitionShip',
    'CannonGalleon',
    'EliteCannonGalleon',
    'Monk',
    'Missionary',
    'TradeCart',
    'TradeCog',
    'FishingShip',
    'TransportShip',
    'Villager',
];

export function getUnitLineIcon(unitLine: UnitLine) {
    const unit = unitLines[unitLine].units[0] as Unit;
    return getUnitIcon(unit);
}

export function getEliteUniqueResearchIcon() {
    return '/units/EliteUniqueResearch.png';
}

export function getUnitIcon(unit: Unit) {
    if (!unitIcons.includes(unit)) return getEliteUniqueResearchIcon();
    return '/units/' + unit + '.png';
}
