# Prevent Fastlane from overwriting README.md
skip_docs

default_platform(:android)

# This should be run after running
# flutter build apk --release
# to build the app using the Flutter toolchain.
platform :android do
  desc 'Push the built release APK to alpha or beta depending on current branch'
  lane :deploy_play_store do
    begin
      upload_to_play_store(
        aab: '../expo-project-cfa0.aab',
        json_key: '../play-store-service-account.json',
        skip_upload_screenshots: true,
        skip_upload_images: true
      )
    rescue => exception
      raise exception unless exception.message.include?('apkUpgradeVersionConflict')
      puts 'Current version already present on the Play Store. Omitting this upload.'
    end
  end
end
