


export const civsData = [
    /* 01 */ 'Britons',
    /* 02 */ 'Franks',
    /* 03 */ 'Goths',
    /* 04 */ 'Teutons',
    /* 05 */ 'Japanese',
    /* 06 */ 'Chinese',
    /* 07 */ 'Byzantines',
    /* 08 */ 'Persians',
    /* 09 */ 'Saracens',
    /* 10 */ 'Turks',
    /* 11 */ 'Vikings',
    /* 12 */ 'Mongols',
    /* 13 */ 'Celts',
    /* 14 */ 'Spanish',
    /* 15 */ 'Aztecs',
    /* 16 */ 'Mayans',
    /* 17 */ 'Huns',
    /* 18 */ 'Koreans',
    /* 19 */ 'Italians',
    /* 20 */ 'Hindustanis',
    /* 21 */ 'Incas',
    /* 22 */ 'Magyars',
    /* 23 */ 'Slavs',
    /* 24 */ 'Portuguese',
    /* 25 */ 'Ethiopians',
    /* 26 */ 'Malians',
    /* 27 */ 'Berbers',
    /* 28 */ 'Khmer',
    /* 29 */ 'Malay',
    /* 30 */ 'Burmese',
    /* 31 */ 'Vietnamese',
    /* 32 */ 'Bulgarians',
    /* 33 */ 'Tatars',
    /* 34 */ 'Cumans',
    /* 35 */ 'Lithuanians',
    /* 36 */ 'Burgundians',
    /* 38 */ 'Poles',
    /* 37 */ 'Sicilians',
    /* 39 */ 'Bohemians',
    /* 40 */ 'Dravidians',
    /* 41 */ 'Bengalis',
    /* 42 */ 'Gurjaras',
    /* 43 */ 'Romans',

    /* 65537 */ 'Random',
    /* 65539 */ 'FullRandom',
    /* 65538 */ 'Mirror',

    /*  */ 'Indians',
] as const;




export const civsData2 = [
    /* 15 */ 'Aztecs',
    /* 41 */ 'Bengalis',
    /* 27 */ 'Berbers',
    /* 39 */ 'Bohemians',
    /* 01 */ 'Britons',
    /* 32 */ 'Bulgarians',
    /* 36 */ 'Burgundians',
    /* 30 */ 'Burmese',
    /* 07 */ 'Byzantines',
    /* 13 */ 'Celts',
    /* 06 */ 'Chinese',
    /* 34 */ 'Cumans',
    /* 40 */ 'Dravidians',
    /* 25 */ 'Ethiopians',
    /* 02 */ 'Franks',
    /* 03 */ 'Goths',
    /* 42 */ 'Gurjaras',
    /* 20 */ 'Hindustanis',
    /* 17 */ 'Huns',
    /* 21 */ 'Incas',
    /* 19 */ 'Italians',
    /* 05 */ 'Japanese',
    /* 28 */ 'Khmer',
    /* 18 */ 'Koreans',
    /* 35 */ 'Lithuanians',
    /* 22 */ 'Magyars',
    /* 29 */ 'Malay',
    /* 26 */ 'Malians',
    /* 16 */ 'Mayans',
    /* 12 */ 'Mongols',
    /* 08 */ 'Persians',
    /* 38 */ 'Poles',
    /* 24 */ 'Portuguese',
    /* 43 */ 'Romans',
    /* 09 */ 'Saracens',
    /* 37 */ 'Sicilians',
    /* 23 */ 'Slavs',
    /* 14 */ 'Spanish',
    /* 33 */ 'Tatars',
    /* 04 */ 'Teutons',
    /* 10 */ 'Turks',
    /* 31 */ 'Vietnamese',
    /* 11 */ 'Vikings',

    /* 65537 */ 'Random',
    /* 65539 */ 'FullRandom',
    /* 65538 */ 'Mirror',

    /*  */ 'Indians',
] as const;

