
const maps = {
    9: "rm_arabia",
    // 10: "Archipelago",
    // 11: "Baltic",
    // 12: "Black Forest",
    // 13: "Coastal",
    // 14: "Continental",
    // 15: "Crater Lake",
    // 16: "Fortress",
    // 17: "Gold Rush",
    // 18: "Highland",
    // 19: "Islands",
    // 20: "Mediterranean",
    // 21: "Migration",
    // 22: "Rivers",
    // 23: "Team Islands",
    // 24: "Full Random",
    // 25: "Scandinavia",
    // 26: "Mongolia",
    // 27: "Yucatan",
    // 28: "Salt Marsh",
    // 29: "Arena",
    // 31: "Oasis",
    // 32: "Ghost Lake",
    // 33: "Nomad",
    // 49: "Iberia",
    // 50: "Britain",
    // 51: "Mideast",
    // 52: "Texas",
    // 53: "Italy",
    // 54: "Central America",
    // 55: "France",
    // 56: "Norse Lands",
    // 57: "Sea of Japan (East Sea)",
    // 58: "Byzantium",
    // 59: "Custom",
    // 60: "Random Land Map",
    // 62: "Random Real World Map",
    // 63: "Blind Random",
    // 65: "Random Special Map",
    // 66: "Random Special Map",
    // 67: "Acropolis",
    // 68: "Budapest",
    // 69: "Cenotes",
    // 70: "City of Lakes",
    // 71: "Golden Pit",
    // 72: "Hideout",
    // 73: "Hill Fort",
    // 74: "Lombardia",
    // 75: "Steppe",
    // 76: "Valley",
    // 77: "MegaRandom",
    // 78: "Hamburger",
    // 79: "CtR Random",
    // 80: "CtR Monsoon",
    // 81: "CtR Pyramid Descent",
    // 82: "CtR Spiral",
    // 83: "Kilimanjaro",
    // 84: "Mountain Pass",
    // 85: "Nile Delta",
    // 86: "Serengeti",
    // 87: "Socotra",
    // 88: "Amazon",
    // 89: "China",
    // 90: "Horn of Africa",
    // 91: "India",
    // 92: "Madagascar",
    // 93: "West Africa",
    // 94: "Bohemia",
    // 95: "Earth",
    // 96: "Canyons",
    // 97: "Enemy Archipelago",
    // 98: "Enemy Islands",
    // 99: "Far Out",
    // 100: "Front Line",
    // 101: "Inner Circle",
    // 102: "Motherland",
    // 103: "Open Plains",
    // 104: "Ring of Water",
    // 105: "Snakepit",
    // 106: "The Eye",
    // 107: "Australia",
    // 108: "Indochina",
    // 109: "Indonesia",
    // 110: "Strait of Malacca",
    // 111: "Philippines",
    // 112: "Bog Islands",
    // 113: "Mangrove Jungle",
    // 114: "Pacific Islands",
    // 115: "Sandbank",
    // 116: "Water Nomad",
    // 117: "Jungle Islands",
    // 118: "Holy Line",
    // 119: "Border Stones",
    // 120: "Yin Yang",
    // 121: "Jungle Lanes",
    // 122: "Alpine Lakes",
    // 123: "Bogland",
    // 124: "Mountain Ridge",
    // 125: "Ravines",
    // 126: "Wolf Hill",
    // 132: "Antarctica",
    // 137: "Custom Map Pool",
    // 139: "Golden Swamp",
    // 140: "Four Lakes",
};

