// Real aoe4 match data from data.aoe4companion.com (match 240377637, profile 7721421).
export const match4v4 = {
    "playerId": 7721421,
    "match": {
        "matchId": 240377637,
        "started": "2026-06-28T14:13:32.000Z",
        "finished": null,
        "leaderboard": "rm_team",
        "leaderboardId": "rm_team",
        "leaderboardName": "Team Ranked",
        "name": "AUTOMATCH",
        "server": null,
        "internalLeaderboardId": 4,
        "map": "westlake",
        "mapName": "West Lake",
        "mapImageUrl": "https://backend.cdn.aoe2companion.com/public/aoe4/maps/westlake.png",
        "mod": false,
        "patch": 1782,
        "pup": false,
        "modMap": null,
        "modTuningPack": null,
        "modGameMode": null,
        "modScenario": null,
        "cheats": false,
        "speedFactor": 1,
        "gameMode": "standard",
        "gameModeName": "Standard",
        "biome": 118812,
        "biomeName": "European Temperate",
        "mapSize": 129303,
        "mapSizeName": "Large (Max. 8 Players)",
        "startingResources": "standard",
        "startingResourcesName": "Standard",
        "startingAge": "age_1",
        "startingAgeName": "Age I",
        "mapState": "concealed",
        "mapStateName": "Concealed",
        "winConditions": [
            "landmarks",
            "sacred",
            "wonder"
        ],
        "winConditionsName": "Landmarks, Sacred, Wonder",
        "teams": [
            {
                "teamId": 0,
                "players": [
                    {
                        "profileId": 8139351,
                        "name": "白白胖胖",
                        "rating": 1219,
                        "ratingDiff": null,
                        "civ": "golden_horde",
                        "civName": "Golden Horde",
                        "civImageUrl": "https://backend.cdn.aoe2companion.com/public/aoe4/civilizations/golden_horde.png",
                        "color": 8,
                        "colorHex": "#F65BB2",
                        "slot": 0,
                        "status": "player",
                        "team": 0,
                        "replay": false,
                        "won": null,
                        "country": "cn",
                        "verified": false
                    },
                    {
                        "profileId": 18654395,
                        "name": "Master Chen",
                        "rating": 1232,
                        "ratingDiff": null,
                        "civ": "english",
                        "civName": "English",
                        "civImageUrl": "https://backend.cdn.aoe2companion.com/public/aoe4/civilizations/english.png",
                        "color": 0,
                        "colorHex": "unknown",
                        "slot": 1,
                        "status": "player",
                        "team": 0,
                        "replay": false,
                        "won": null,
                        "country": "cn",
                        "verified": false
                    },
                    {
                        "profileId": 19092763,
                        "name": "Broken",
                        "rating": 1189,
                        "ratingDiff": null,
                        "civ": "knights_templar",
                        "civName": "Knights Templar",
                        "civImageUrl": "https://backend.cdn.aoe2companion.com/public/aoe4/civilizations/knights_templar.png",
                        "color": 2,
                        "colorHex": "#FF3B30",
                        "slot": 2,
                        "status": "player",
                        "team": 0,
                        "replay": false,
                        "won": null,
                        "country": "cn",
                        "verified": false
                    },
                    {
                        "profileId": 6970078,
                        "name": "你们开小号在鱼塘炸鱼",
                        "rating": 912,
                        "ratingDiff": null,
                        "civ": "french",
                        "civName": "French",
                        "civImageUrl": "https://backend.cdn.aoe2companion.com/public/aoe4/civilizations/french.png",
                        "color": 0,
                        "colorHex": "unknown",
                        "slot": 3,
                        "status": "player",
                        "team": 0,
                        "replay": false,
                        "won": null,
                        "country": "cn",
                        "verified": false
                    }
                ]
            },
            {
                "teamId": 1,
                "players": [
                    {
                        "profileId": 25567764,
                        "name": "MEHTERTV",
                        "rating": 1055,
                        "ratingDiff": null,
                        "civ": "holy_roman_empire",
                        "civName": "Holy Roman Empire",
                        "civImageUrl": "https://backend.cdn.aoe2companion.com/public/aoe4/civilizations/holy_roman_empire.png",
                        "color": 4,
                        "colorHex": "#00C700",
                        "slot": 4,
                        "status": "player",
                        "team": 1,
                        "replay": false,
                        "won": null,
                        "country": "tr",
                        "verified": false
                    },
                    {
                        "profileId": 7721421,
                        "name": "Beasty",
                        "rating": 1025,
                        "ratingDiff": null,
                        "civ": "abbasid_dynasty",
                        "civName": "Abbasid Dynasty",
                        "civImageUrl": "https://backend.cdn.aoe2companion.com/public/aoe4/civilizations/abbasid_dynasty.png",
                        "color": 3,
                        "colorHex": "#EBD300",
                        "slot": 5,
                        "status": "player",
                        "team": 1,
                        "replay": false,
                        "won": null,
                        "country": "de",
                        "verified": false
                    },
                    {
                        "profileId": 21050922,
                        "name": "HALASKAR GAZİ",
                        "rating": 1010,
                        "ratingDiff": null,
                        "civ": "english",
                        "civName": "English",
                        "civImageUrl": "https://backend.cdn.aoe2companion.com/public/aoe4/civilizations/english.png",
                        "color": 0,
                        "colorHex": "unknown",
                        "slot": 6,
                        "status": "player",
                        "team": 1,
                        "replay": false,
                        "won": null,
                        "country": "tr",
                        "verified": false
                    },
                    {
                        "profileId": 14926729,
                        "name": "Keycoder",
                        "rating": 1103,
                        "ratingDiff": null,
                        "civ": "ottomans",
                        "civName": "Ottomans",
                        "civImageUrl": "https://backend.cdn.aoe2companion.com/public/aoe4/civilizations/ottomans.png",
                        "color": 7,
                        "colorHex": "#FF6600",
                        "slot": 7,
                        "status": "player",
                        "team": 1,
                        "replay": false,
                        "won": null,
                        "country": "tr",
                        "verified": false
                    }
                ]
            }
        ]
    }
};
