import { ILobbiesMatch, IMatchNew } from '@app/api/helper/api.types';
import { parseISO } from 'date-fns';

// export const testMatch: IMatchNew = {
//     "matchId": 405747136,
//     "started": parseISO("2025-07-12T13:59:03.000Z"),
//     "finished": undefined,
//     "leaderboardId": "unranked",
//     "leaderboardName": "Unranked",
//     "name": "3v3 noobs GREEN PING",
//     "server": "westeurope",
//     "internalLeaderboardId": 0,
//     "privacy": 2,
//     "mod": false,
//     "map": "rm_michi",
//     "mapName": "Michi",
//     "mapImageUrl": "https://frontend.cdn.aoe2companion.com/public/aoe2/de/maps/rm_michi.png",
//     "difficulty": 3,
//     "difficultyName": "Standard",
//     "startingAge": 0,
//     "startingAgeName": "Standard",
//     "fullTechTree": false,
//     "allowCheats": false,
//     "empireWarsMode": true,
//     "endingAge": 0,
//     "endingAgeName": "Standard",
//     "gameMode": "random_map",
//     "gameModeName": "Random Map",
//     "lockSpeed": true,
//     "lockTeams": false,
//     "mapSize": 200,
//     "mapSizeName": "Normal (6 player) [200]",
//     "population": 225,
//     "hideCivs": false,
//     "recordGame": true,
//     "regicideMode": true,
//     "gameVariant": 2,
//     "resources": 0,
//     "resourcesName": "Standard",
//     "sharedExploration": false,
//     "speed": 2,
//     "speedName": "Normal",
//     "suddenDeathMode": true,
//     "antiquityMode": true,
//     "civilizationSet": 1,
//     "civilizationSetName": "Age of Empires II",
//     "teamPositions": false,
//     "teamTogether": true,
//     "treatyLength": 0,
//     "turboMode": true,
//     "victory": 1,
//     "victoryName": "Conquest",
//     "revealMap": 1,
//     "revealMapName": "Explored",
//     "scenario": undefined,
//     "password": false,
//     "modDataset": undefined,
//     "totalSlotCount": 8,
//     "blockedSlotCount": 6,
//     "averageRating": 1223,
//     "teams": [
//         {
//             "teamId": 1,
//             "players": [
//                 {
//                     "profileId": 19912011,
//                     "name": "Black Mamba",
//                     "rating": 1313,
//                     "rank": 21291,
//                     "civ": "persians",
//                     "civName": "Persians",
//                     "civImageUrl": "https://frontend.cdn.aoe2companion.com/public/aoe2/de/civilizations/persians.png",
//                     "color": 2,
//                     "colorHex": "#FF0000",
//                     "slot": 0,
//                     "status": "player",
//                     "team": 1,
//                     "country": "es",
//                     "verified": false,
//                     "games": 627,
//                     "wins": 321,
//                     "losses": 306,
//                     "drops": 7,
//                     "teamName": "Team 1"
//                 },
//                 {
//                     "profileId": 20399035,
//                     "name": "Wanzer",
//                     "rating": 1297,
//                     "rank": 23635,
//                     "civ": "gurjaras",
//                     "civName": "Gurjaras",
//                     "civImageUrl": "https://frontend.cdn.aoe2companion.com/public/aoe2/de/civilizations/gurjaras.png",
//                     "color": 6,
//                     "colorHex": "#FF57B3",
//                     "slot": 1,
//                     "status": "player",
//                     "team": 1,
//                     "country": undefined,
//                     "verified": false,
//                     "games": 152,
//                     "wins": 85,
//                     "losses": 67,
//                     "drops": 3,
//                     "teamName": "Team 1"
//                 },
//                 {
//                     "profileId": 2307236,
//                     "name": "danidiro",
//                     "rating": 1359,
//                     "rank": 15346,
//                     "civ": "turks",
//                     "civName": "Turks",
//                     "civImageUrl": "https://frontend.cdn.aoe2companion.com/public/aoe2/de/civilizations/turks.png",
//                     "color": 4,
//                     "colorHex": "#FFFF00",
//                     "slot": 2,
//                     "status": "player",
//                     "team": 1,
//                     "country": undefined,
//                     "verified": false,
//                     "games": 164,
//                     "wins": 119,
//                     "losses": 45,
//                     "drops": 7,
//                     "teamName": "Team 1"
//                 }
//             ]
//         },
//         {
//             "teamId": 2,
//             "players": [
//                 {
//                     "profileId": 12524889,
//                     "name": "rhyminS8827",
//                     "rating": 1025,
//                     "rank": 101422,
//                     "civ": "teutons",
//                     "civName": "Teutons",
//                     "civImageUrl": "https://frontend.cdn.aoe2companion.com/public/aoe2/de/civilizations/teutons.png",
//                     "color": 1,
//                     "colorHex": "#405BFF",
//                     "slot": 3,
//                     "status": "player",
//                     "team": 2,
//                     "country": undefined,
//                     "verified": false,
//                     "games": 97,
//                     "wins": 31,
//                     "losses": 66,
//                     "drops": 13,
//                     "teamName": "Team 2"
//                 },
//                 {
//                     "profileId": 9130671,
//                     "name": "sanmanuel",
//                     "rating": 1047,
//                     "rank": 88842,
//                     "civ": "slavs",
//                     "civName": "Slavs",
//                     "civImageUrl": "https://frontend.cdn.aoe2companion.com/public/aoe2/de/civilizations/slavs.png",
//                     "color": 3,
//                     "colorHex": "#00FF00",
//                     "slot": 4,
//                     "status": "player",
//                     "team": 2,
//                     "country": "us",
//                     "verified": false,
//                     "games": 589,
//                     "wins": 167,
//                     "losses": 422,
//                     "drops": 8,
//                     "teamName": "Team 2"
//                 },
//                 {
//                     "profileId": 9604377,
//                     "name": "85051",
//                     "rating": 1299,
//                     "rank": 23303,
//                     "civ": "poles",
//                     "civName": "Poles",
//                     "civImageUrl": "https://frontend.cdn.aoe2companion.com/public/aoe2/de/civilizations/poles.png",
//                     "color": 5,
//                     "colorHex": "#00FFFF",
//                     "slot": 5,
//                     "status": "player",
//                     "team": 2,
//                     "country": "cn",
//                     "verified": false,
//                     "games": 1833,
//                     "wins": 868,
//                     "losses": 965,
//                     "drops": 49,
//                     "teamName": "Team 2"
//                 }
//             ]
//         }
//     ]
// };
//
// export const testLobby: ILobbiesMatch = {
//     "matchId": 405736139,
//     "started": undefined,
//     "finished": undefined,
//     "leaderboardId": "unranked",
//     "leaderboardName": "Unranked",
//     "name": "4 vs 4 BF FAST noobs ",
//     "server": "koreacentral",
//     "internalLeaderboardId": 0,
//     "privacy": 2,
//     "mod": false,
//     "map": "rm_black-forest",
//     "mapName": "Black Forest",
//     "mapImageUrl": "https://frontend.cdn.aoe2companion.com/public/aoe2/de/maps/rm_black-forest.png",
//     "difficulty": 3,
//     "difficultyName": "Standard",
//     "startingAge": 0,
//     "startingAgeName": "Standard",
//     "fullTechTree": false,
//     "allowCheats": false,
//     "empireWarsMode": true,
//     "endingAge": 0,
//     "endingAgeName": "Standard",
//     "gameMode": "random_map",
//     "gameModeName": "Random Map",
//     "lockSpeed": true,
//     "lockTeams": false,
//     "mapSize": 240,
//     "mapSizeName": "Huge [240]",
//     "population": 500,
//     "hideCivs": true,
//     "recordGame": true,
//     "regicideMode": true,
//     "gameVariant": 2,
//     "resources": 0,
//     "resourcesName": "Standard",
//     "sharedExploration": false,
//     "speed": 3,
//     "speedName": "Fast",
//     "suddenDeathMode": true,
//     "antiquityMode": true,
//     "civilizationSet": 1,
//     "civilizationSetName": "Age of Empires II",
//     "teamPositions": false,
//     "teamTogether": true,
//     "treatyLength": 0,
//     "turboMode": true,
//     "victory": 9,
//     "victoryName": "Standard",
//     "revealMap": 1,
//     "revealMapName": "Explored",
//     "scenario": undefined,
//     "password": false,
//     "modDataset": undefined,
//     "totalSlotCount": 8,
//     "blockedSlotCount": 7,
//     "averageRating": 1244,
//     "players": [
//         {
//             "profileId": 897802,
//             "name": "lI9185ZD36",
//             "rating": 1263,
//             "rank": 28866,
//             "civ": undefined,
//             "civName": "Hidden",
//             "civImageUrl": undefined,
//             "color": undefined,
//             "colorHex": "unknown",
//             "slot": 0,
//             "status": "player",
//             "team": -1,
//             "country": "kr",
//             "verified": false,
//             "games": 1166,
//             "wins": 605,
//             "losses": 561,
//             "drops": 27,
//             "teamName": "Random Team",
//             "matchId": 405736139
//         },
//         {
//             "profileId": 11957574,
//             "name": "Pablo Emilio Escobar Gaviria",
//             "civ": undefined,
//             "civName": "Hidden",
//             "civImageUrl": undefined,
//             "color": undefined,
//             "colorHex": "unknown",
//             "slot": 1,
//             "status": "player",
//             "team": -1,
//             "country": "tr",
//             "verified": false,
//             "games": 0,
//             "wins": 0,
//             "losses": 0,
//             "drops": 0,
//             "teamName": "Random Team",
//             "matchId": 405736139
//         },
//         {
//             "profileId": 18182898,
//             "name": "3m1R",
//             "rating": 1439,
//             "rank": 7932,
//             "civ": undefined,
//             "civName": "Hidden",
//             "civImageUrl": undefined,
//             "color": 3,
//             "colorHex": "#00FF00",
//             "slot": 2,
//             "status": "player",
//             "team": -1,
//             "country": "tr",
//             "verified": false,
//             "games": 2257,
//             "wins": 1328,
//             "losses": 929,
//             "drops": 160,
//             "teamName": "Random Team",
//             "matchId": 405736139
//         },
//         {
//             "profileId": 19004851,
//             "name": "danganharmy",
//             "rating": 1049,
//             "rank": 93528,
//             "civ": undefined,
//             "civName": "Hidden",
//             "civImageUrl": undefined,
//             "color": undefined,
//             "colorHex": "unknown",
//             "slot": 3,
//             "status": "player",
//             "team": 2,
//             "country": "vn",
//             "verified": false,
//             "games": 1283,
//             "wins": 645,
//             "losses": 638,
//             "drops": 30,
//             "teamName": "Team 2",
//             "matchId": 405736139
//         },
//         {
//             "profileId": 17938984,
//             "name": "Morimer",
//             "rating": 1196,
//             "rank": 41895,
//             "civ": undefined,
//             "civName": "Hidden",
//             "civImageUrl": undefined,
//             "color": undefined,
//             "colorHex": "unknown",
//             "slot": 4,
//             "status": "player",
//             "team": -1,
//             "country": "ru",
//             "verified": false,
//             "games": 447,
//             "wins": 160,
//             "losses": 287,
//             "drops": 20,
//             "teamName": "Random Team",
//             "matchId": 405736139
//         },
//         {
//             "profileId": 4111455,
//             "name": "2yearhk",
//             "rating": 1339,
//             "rank": 17776,
//             "civ": undefined,
//             "civName": "Hidden",
//             "civImageUrl": undefined,
//             "color": 6,
//             "colorHex": "#FF57B3",
//             "slot": 5,
//             "status": "player",
//             "team": -1,
//             "country": "hk",
//             "verified": false,
//             "games": 855,
//             "wins": 536,
//             "losses": 319,
//             "drops": 9,
//             "teamName": "Random Team",
//             "matchId": 405736139
//         },
//         {
//             "profileId": -1,
//             "name": "Open",
//             "civ": undefined,
//             "civName": "Hidden",
//             "civImageUrl": undefined,
//             "color": undefined,
//             "colorHex": "unknown",
//             "slot": 6,
//             "status": "player",
//             "country": undefined,
//             "verified": false,
//             "games": 0,
//             "wins": 0,
//             "losses": 0,
//             "drops": 0,
//             "teamName": "[team.unknown]",
//             "matchId": 405736139
//         },
//         {
//             "profileId": 8586150,
//             "name": "Rei",
//             "rating": 1176,
//             "rank": 46414,
//             "civ": undefined,
//             "civName": "Hidden",
//             "civImageUrl": undefined,
//             "color": undefined,
//             "colorHex": "unknown",
//             "slot": 7,
//             "status": "player",
//             "team": -1,
//             "country": "de",
//             "verified": false,
//             "games": 353,
//             "wins": 109,
//             "losses": 244,
//             "drops": 6,
//             "teamName": "Random Team",
//             "matchId": 405736139
//         }
//     ]
// };
