import {IMatch} from "@nex/data";
import {fromUnixTime} from "date-fns";
import {getHost} from "./host";
import {fetchJson} from "./util";
import {IMatchRaw} from '@nex/data/api';


function convertTimestampsToDates(json: IMatchRaw): IMatch {
    return {
        ...json,
        started: fromUnixTime(json.started),
        finished: fromUnixTime(json.finished),
        opened: fromUnixTime(json.opened),
    };
}

const fakeData = {
    "profile_id": 223576, "steam_id": "76561198001031686", "name": "Sihing Mo", "clan": "AE2C",
    "country": "DE",
    "last_match": {
        "match_id": "73333563",
        "lobby_id": null,
        "match_uuid": "ba8e5a40-b8c0-674b-b40f-8aaacd2364bf",
        "version": "45340",
        "name": "AUTOMATCH",
        "num_players": 2,
        "num_slots": 2,
        "average_rating": null,
        "cheats": false,
        "full_tech_tree": false,
        "ending_age": 5,
        "expansion": null,
        "game_type": 0,
        "has_custom_content": null,
        "has_password": true,
        "lock_speed": true,
        "lock_teams": true,
        "map_size": 0,
        "map_type": 9,
        "pop": 200,
        "ranked": true,
        "leaderboard_id": 3,
        "rating_type": 2,
        "resources": 1,
        "rms": null,
        "scenario": null,
        "server": "ukwest",
        "shared_exploration": false,
        "speed": 2,
        "starting_age": 2,
        "team_together": true,
        "team_positions": true,
        "treaty_length": 0,
        "turbo": false,
        "victory": 1,
        "victory_time": 0,
        "visibility": 0,
        "opened": 1614355718,
        "started": 1614355718,
        "finished": 1614357103,
        "players": [{
            "profile_id": 1474717,
            "steam_id": "76561198055601120",
            "name": "Grinden",
            "clan": null,
            "country": null,
            "slot": 1,
            "slot_type": 1,
            "rating": 1199,
            "rating_change": null,
            "games": 26+19,
            "wins": 26,
            "streak": null,
            "drops": null,
            "color": 2,
            "team": 1,
            "civ": 12,
            "won": true
        }, {
            "profile_id": 223576,
            "steam_id": "76561198001031686",
            "name": "Sihing Mo",
            "clan": null,
            "country": null,
            "slot": 2,
            "slot_type": 1,
            "rating": 1191,
            "rating_change": null,
            "games": 114+115,
            "wins": 114,
            "streak": null,
            "drops": null,
            "color": 3,
            "team": 2,
            "civ": 2,
            "won": false
        }]
    }
};

const fakeData1 = fakeData.last_match;
const fakeData2 = {
    "match_id": "72704893",
    "lobby_id": null,
    "match_uuid": "347e6009-d6f5-884f-ab05-42ae220e84f1",
    "version": "45340",
    "name": "AUTOMATCH",
    "num_players": 8,
    "num_slots": 8,
    "average_rating": null,
    "cheats": false,
    "full_tech_tree": false,
    "ending_age": 5,
    "expansion": null,
    "game_type": 0,
    "has_custom_content": null,
    "has_password": true,
    "lock_speed": true,
    "lock_teams": true,
    "map_size": 4,
    "map_type": 33,
    "pop": 200,
    "ranked": true,
    "leaderboard_id": 4,
    "rating_type": 4,
    "resources": 1,
    "rms": null,
    "scenario": null,
    "server": "ukwest",
    "shared_exploration": false,
    "speed": 2,
    "starting_age": 2,
    "team_together": true,
    "team_positions": true,
    "treaty_length": 0,
    "turbo": false,
    "victory": 1,
    "victory_time": 0,
    "visibility": 0,
    "opened": "2021-02-23T12:25:04.000Z",
    "started": "2021-02-23T12:25:04.000Z",
    "finished": "2021-02-23T12:46:57.000Z",
    "players": [{
        "profile_id": 209525,
        "steam_id": "76561197995781128",
        "name": "aoe2companion.com",
        "clan": null,
        "country": "DE",
        "slot": 1,
        "slot_type": 1,
        "rating": 2187,
        "rating_change": -10,
        "games": 234,
        "wins": 150,
        "streak": null,
        "drops": null,
        "color": 6,
        "team": 1,
        "civ": 11,
        "won": false
    }, {
        "profile_id": 5061049,
        "steam_id": "76561199140652291",
        "name": "PlayingOpenMaps",
        "clan": null,
        "country": "GB",
        "slot": 2,
        "slot_type": 1,
        "rating": 2016,
        "rating_change": 29,
        "games": 412,
        "wins": 201,
        "streak": null,
        "drops": null,
        "color": 3,
        "team": 2,
        "civ": 31,
        "won": true
    }, {
        "profile_id": 223576,
        "steam_id": "76561198001031686",
        "name": "Sihing Mo",
        "clan": null,
        "country": "DE",
        "slot": 3,
        "slot_type": 1,
        "rating": 2186,
        "rating_change": -10,
        "games": 312,
        "wins": 155,
        "streak": null,
        "drops": null,
        "color": 8,
        "team": 1,
        "civ": 2,
        "won": false
    }, {
        "profile_id": 909332,
        "steam_id": "76561198077883114",
        "name": "TheXnore",
        "clan": null,
        "country": "LV",
        "slot": 4,
        "slot_type": 1,
        "rating": 2216,
        "rating_change": 11,
        "games": 622,
        "wins": 305,
        "streak": null,
        "drops": null,
        "color": 5,
        "team": 2,
        "civ": 35,
        "won": true
    }, {
        "profile_id": 1867920,
        "steam_id": "76561198008263520",
        "name": "Doni",
        "clan": null,
        "country": "FR",
        "slot": 5,
        "slot_type": 1,
        "rating": 2091,
        "rating_change": -10,
        "games": 130,
        "wins": 65,
        "streak": null,
        "drops": null,
        "color": 2,
        "team": 1,
        "civ": 11,
        "won": false
    }, {
        "profile_id": 907050,
        "steam_id": "76561198960399602",
        "name": "Gothic_Paladin",
        "clan": null,
        "country": "LV",
        "slot": 6,
        "slot_type": 1,
        "rating": 2225,
        "rating_change": 10,
        "games": 476,
        "wins": 234,
        "streak": null,
        "drops": null,
        "color": 1,
        "team": 2,
        "civ": 11,
        "won": true
    }, {
        "profile_id": 2531706,
        "steam_id": "76561198971846248",
        "name": "Juan22",
        "clan": null,
        "country": "AR",
        "slot": 7,
        "slot_type": 1,
        "rating": 2136,
        "rating_change": -8,
        "games": 750,
        "wins": 382,
        "streak": null,
        "drops": null,
        "color": 4,
        "team": 1,
        "civ": 36,
        "won": false
    }, {
        "profile_id": 4695892,
        "steam_id": "76561199075612228",
        "name": "Vip go",
        "clan": null,
        "country": "AR",
        "slot": 8,
        "slot_type": 1,
        "rating": 2140,
        "rating_change": 13,
        "games": 370,
        "wins": 177,
        "streak": null,
        "drops": null,
        "color": 7,
        "team": 2,
        "civ": 2,
        "won": true
    }],
    "source": "aoe2net"
};

export async function fetchLastMatch(game: string, profile_id: number) {
    // const url = getHost('aoe2net') + `api/player/lastmatch?game=${game}&profile_id=${profile_id}`;
    // const json = await fetchJson('fetchLastMatch', url);

    // console.log(JSON.stringify(json));

    return convertTimestampsToDates(fakeData2 as any);

    // return convertTimestampsToDates(json.last_match);
}
