// File hash: c4b16dc667bf374d88a8e9edb710f86cab5fb4530e74ba3250a2adf25edd262a
/*Automatically generated by expo-type-information.*/

import { ViewProps } from 'react-native';

import { NativeModule } from 'expo';
