// File hash: 78c7991c2fe2cd365ea36707f4a0ef3c230aa88e20d809800418e71ef97013f1
/*Automatically generated by expo-type-information.*/

import { requireNativeModule, NativeModule } from 'expo';

export declare class AppUpdate extends NativeModule {
  readonly Hello: unknown /*The type couldn't be resolved automatically.*/;
}

const _default: AppUpdate = requireNativeModule<AppUpdate>('AppUpdate');
export default _default;
