// File hash: 78c7991c2fe2cd365ea36707f4a0ef3c230aa88e20d809800418e71ef97013f1
/*Automatically generated by expo-type-information.*/

import { requireNativeModule, NativeModule } from 'expo';
import { AppUpdateInfo } from '@/modules/app-update/src/AppUpdate.types';

export declare class AppUpdate extends NativeModule {
    readonly Hello: unknown /*The type couldn't be resolved automatically.*/;
    getAppUpdateInfo(): Promise<AppUpdateInfo>;
    doAppUpdate(): void;
}

const _default: AppUpdate = requireNativeModule<AppUpdate>('AppUpdate');
export default _default;

// import { NativeModule, requireNativeModule } from 'expo-modules-core';
// import { AppUpdateInfo, ExpoAppUpdateModuleEvents } from './ExpoAppUpdate.types';
//
// declare class ExpoAppUpdateModule extends NativeModule<ExpoAppUpdateModuleEvents> {
//     getAppUpdateInfo(): Promise<AppUpdateInfo>;
//     doAppUpdate(): void;
// }
//
// // This call loads the native module object from the JSI.
// export default requireNativeModule<ExpoAppUpdateModule>('ExpoAppUpdate');
